#
#yeamimhossainsajid_db_user
#aAusbiTqsgFozyv1
spring.application.name=product-service
spring.data.mongodb.uri=mongodb+srv://yeamimhossainsajid_db_user:aAusbiTqsgFozyv1@sajid000.auijikj.mongodb.net/mydb?retryWrites=true&w=majority&appName=Sajid000



